using System.Globalization;
using System.Text.Json;
using ATrade.Analysis;

namespace ATrade.Analysis.Lean;

public static class LeanAnalysisResultParser
{
    public static AnalysisResult Parse(
        LeanRuntimeExecutionResult executionResult,
        AnalysisRequest request,
        LeanInputData input,
        AnalysisEngineMetadata engineMetadata,
        AnalysisDataSource source)
    {
        ArgumentNullException.ThrowIfNull(executionResult);
        ArgumentNullException.ThrowIfNull(request);
        ArgumentNullException.ThrowIfNull(input);
        ArgumentNullException.ThrowIfNull(engineMetadata);
        ArgumentNullException.ThrowIfNull(source);

        var payload = FindResultPayload(executionResult.StandardOutput, executionResult.StandardError);
        using var document = JsonDocument.Parse(payload);
        var root = document.RootElement;
        var generatedAtUtc = ReadDateTimeOffset(root, "generatedAtUtc") ?? DateTimeOffset.UtcNow;

        return new AnalysisResult(
            AnalysisResultStatuses.Completed,
            engineMetadata,
            source,
            request.Symbol,
            request.Timeframe,
            generatedAtUtc,
            ReadSignals(root),
            ReadMetrics(root),
            ReadBacktest(root, input),
            Error: null);
    }

    private static string FindResultPayload(params string[] outputs)
    {
        foreach (var output in outputs.Where(static output => !string.IsNullOrWhiteSpace(output)))
        {
            var lines = output.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var line in lines.Reverse())
            {
                var markerIndex = line.IndexOf(LeanAlgorithmTemplate.ResultMarker, StringComparison.Ordinal);
                if (markerIndex < 0)
                {
                    continue;
                }

                return line[(markerIndex + LeanAlgorithmTemplate.ResultMarker.Length)..].Trim();
            }
        }

        throw new LeanAnalysisResultParseException("LEAN runtime completed without emitting an ATrade analysis result marker.");
    }

    private static IReadOnlyList<AnalysisSignal> ReadSignals(JsonElement root)
    {
        if (!root.TryGetProperty("signals", out var signalsElement) || signalsElement.ValueKind != JsonValueKind.Array)
        {
            return Array.Empty<AnalysisSignal>();
        }

        return signalsElement.EnumerateArray()
            .Select(static signal => new AnalysisSignal(
                ReadDateTimeOffset(signal, "time") ?? DateTimeOffset.UtcNow,
                ReadString(signal, "kind", "signal"),
                ReadString(signal, "direction", "neutral"),
                ReadDecimal(signal, "confidence"),
                ReadString(signal, "rationale", "Generated by LEAN analysis.")))
            .ToArray();
    }

    private static IReadOnlyList<AnalysisMetric> ReadMetrics(JsonElement root)
    {
        if (!root.TryGetProperty("metrics", out var metricsElement) || metricsElement.ValueKind != JsonValueKind.Array)
        {
            return Array.Empty<AnalysisMetric>();
        }

        return metricsElement.EnumerateArray()
            .Select(static metric => new AnalysisMetric(
                ReadString(metric, "name", "metric"),
                ReadDecimal(metric, "value"),
                ReadNullableString(metric, "unit")))
            .ToArray();
    }

    private static BacktestSummary ReadBacktest(JsonElement root, LeanInputData input)
    {
        if (!root.TryGetProperty("backtest", out var backtestElement) || backtestElement.ValueKind != JsonValueKind.Object)
        {
            return new BacktestSummary(
                input.StartUtc,
                input.EndUtc,
                InitialCapital: 100_000m,
                FinalEquity: 100_000m,
                TotalReturnPercent: 0m,
                TradeCount: 0,
                WinRatePercent: 0m);
        }

        return new BacktestSummary(
            ReadDateTimeOffset(backtestElement, "startUtc") ?? input.StartUtc,
            ReadDateTimeOffset(backtestElement, "endUtc") ?? input.EndUtc,
            ReadDecimal(backtestElement, "initialCapital"),
            ReadDecimal(backtestElement, "finalEquity"),
            ReadDecimal(backtestElement, "totalReturnPercent"),
            ReadInt32(backtestElement, "tradeCount"),
            ReadDecimal(backtestElement, "winRatePercent"));
    }

    private static string ReadString(JsonElement element, string propertyName, string fallback) =>
        ReadNullableString(element, propertyName) ?? fallback;

    private static string? ReadNullableString(JsonElement element, string propertyName)
    {
        return element.TryGetProperty(propertyName, out var property) && property.ValueKind == JsonValueKind.String
            ? property.GetString()
            : null;
    }

    private static DateTimeOffset? ReadDateTimeOffset(JsonElement element, string propertyName)
    {
        var value = ReadNullableString(element, propertyName);
        return DateTimeOffset.TryParse(value, CultureInfo.InvariantCulture, DateTimeStyles.AssumeUniversal, out var parsed)
            ? parsed.ToUniversalTime()
            : null;
    }

    private static decimal ReadDecimal(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var property))
        {
            return 0m;
        }

        if (property.ValueKind == JsonValueKind.Number && property.TryGetDecimal(out var decimalValue))
        {
            return decimalValue;
        }

        if (property.ValueKind == JsonValueKind.String && decimal.TryParse(property.GetString(), NumberStyles.Number, CultureInfo.InvariantCulture, out var stringValue))
        {
            return stringValue;
        }

        return 0m;
    }

    private static int ReadInt32(JsonElement element, string propertyName)
    {
        if (!element.TryGetProperty(propertyName, out var property))
        {
            return 0;
        }

        if (property.ValueKind == JsonValueKind.Number && property.TryGetInt32(out var intValue))
        {
            return intValue;
        }

        if (property.ValueKind == JsonValueKind.String && int.TryParse(property.GetString(), NumberStyles.Integer, CultureInfo.InvariantCulture, out var stringValue))
        {
            return stringValue;
        }

        return 0;
    }
}

public sealed class LeanAnalysisResultParseException(string message) : Exception(message);
